### PR TITLE
Added contributing rules and template SVG

### PR DESCRIPTION
**Pull request by SomeRandomGameDev**
- Added a remainder on how use GitHub for contributing.
 - Added a template SVG containing licence metadata for Create Commons 3.0 (see #138).

### CODE REVIEW

**Comment by Evolena** [comment]
I know little about licensing, but I'm worried that the template is already near 1kb, when some existing icons are only 300-400 Bytes.

**Comment by SomeRandomGameDev** [comment]
Unfortunately, it is the size of the license metadata. But that's all they are: metadata. It is not active/drawing data.

**Comment by Evolena** [comment]
Yes, but I've the idea of providing a [TiddlyWiki](http://tiddlywiki.com/) plugin for using the icons in a wiki, and in this case each icon svg element will be embedded inside a single html file. As all the 2200 icons already weight 5Mo in my first test, the icons wouldn't be shipped inside the plugin, but drag-and-droppable or exportable from the plugin demo site. But even this way, the weight adds quickly.

Of course, I could remove the metadata from each individual icon. There must be a way to provide the information in another form into the licensing information of the plugin (which currently looks like the infos in the "about" page of game-icons.net) ?

As soon as I will have finalized some remaining features for what I'm looking to achieve (customizable background, size and colors when adding an icon to an article), and before releasing the plugin, I've planned to share a link to show the result to @Delapouite and ask for advice, especially on licensing aspects.

**Comment by SomeRandomGameDev** [comment]
I get your point. For a repo like github, a single license file would be sufficient. For a wiki, acknowledging the content as associated to the license is also sufficient. But when delivering the icons as it is done with the game-icons website, the meta data have to be included in the SVG (and the PNG as well).
To sum up, I'm definitely ok with removing metadata from the template. But one has to keep in mind that licensing has to be at some point.

**Comment by SomeRandomGameDev** [comment]
You know what ? I've got the feeling it never matters :)

**Pull request closed without merging**
