### PR TITLE
tap icons

### PR DESCRIPTION
**Pull request by andymeneely**
Inspired by MTG's "tap" mechanic, might help with request #825 

image

### CODE REVIEW

**Comment by aloisdg** [comment]
Did you check if WotC copyrigh the tap symbol?

**Comment by Zireael07** [comment]
The patent on tap in MTG context has expired some time ago.

**Comment by andymeneely** [comment]
@aloisdg I did not. I'll see what I can look into.

@Zireael07 Do you have a source for that info?

**Comment by andymeneely** [comment]
Wow I didn't realize that patenting the "tap" mechanic was a whole... thing. 

So I guess USPTO 5,662,332 covered this and it has expired. The patent is much more specific than just rotating a card to mark it, and the icon isn't included in that patent (or others that I searched for). 

But, icons might be trademarked, so I looked into the [USPTO TESS search engine](https://tmsearch.uspto.gov/bin/gate.exe?f=tess&state=4810:o956q2.2.6) (is that a `.exe` in the url??) and the only Wizards of the Coast icons I could find were literally depicting Wizards of the Coast. I see plenty of people responding that the icon itself is trademarked, but nobody cites a source. To be fair, I'm not well-practiced at searching for trademarks, patents, and registered copyrights.

I mean... it's just a bendy arrow. But I also feel like, given the history of this thing in particular I'd be okay with not accepting it. I'll close it for now but if anyone wants to reopen it that's fine. Heck, if someone else wants their name attached to this go ahead and steal it. 

FWIW, I didn't trace things I just drew them fresh.

**Pull request closed without merging**
